services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ../../env/.env.dev
    volumes:
      - ./postgres/custom_postgresql.conf:/etc/postgresql/postgresql.conf
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgresql
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

volumes:
  pgdata:
  pglogs:

# Run : docker-compose -f docker/dev/docker-compose.yml up -d