services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ../../env/.env.dev
    volumes:
      - ./postgres/custom_postgresql.conf:/etc/postgresql/postgresql.conf
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgresql
    # 명시적으로 conf 파일의 경로를 지정해줘야 마운트 한 postgresql.conf가 적용이 된다
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  pglogs:
  redisdata:

# Run : docker-compose -f docker/dev/docker-compose.yml up -d