version: "3.8"
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ../../env/.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

# Run : docker-compose -f docker/dev/docker-compose.yml up -d